const ADD_TO_BASKET = 'ADD_TO_BASKET';
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
const EMPTY_BASKET = 'EMPTY_BASKET';
const SET_USER = 'SET_USER';

export default {
  ADD_TO_BASKET,
  REMOVE_FROM_BASKET,
  EMPTY_BASKET,
  SET_USER,
};
